---

- block:
    - include_tasks: context.yml

    - include_tasks: context_service.yml


    - name: "set has_git_deploy_{{ git_deploy_name }} to true"
      set_fact:
        "has_git_deploy_{{ git_deploy_name }}": true

  when: git_deploy_name is defined and git_deploy_name

# - block:

#     - include_tasks: context.yml

#     - include_tasks: context_service.yml

#     - include_tasks: mandatory.yml

#     - include_tasks: app_dir.yml

#     - include_tasks: app_user.yml

#     - include_tasks: app_packages.yml

#     - include_tasks: app_workspace.yml

#     # - include_tasks: app_db.yml

#     - include_tasks: app_nginx.yml

#     - include_tasks: app_rails.yml

#     - include_tasks: app_service.yml

#   when: want_app

