---

- block:
    - include_tasks: context.yml

    - include_tasks: context_service.yml

    - include_tasks: install_packages.yml

    - include_tasks: setup_git_part.yml

    - include_tasks: setup_run_part.yml

    - include_tasks: setup_app_part.yml


    - name: "set has_git_deploy_{{ git_deploy_name }} to true"
      set_fact:
        "has_git_deploy_{{ git_deploy_name }}": true

  when: git_deploy_name is defined and git_deploy_name
